### PR TITLE
Make the Add example generic over the input/output type

### PR DESCRIPTION
**Pull request by cbourjau**
This fails with a cryptic ORT error:

```
self = <onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x1121b09d0>, providers = []
provider_options = [], disabled_optimizers = None

    def _create_inference_session(self, providers, provider_options, disabled_optimizers=None):
        available_providers = C.get_available_providers()

        # Tensorrt can fall back to CUDA. All others fall back to CPU.
        if "TensorrtExecutionProvider" in available_providers:
            self._fallback_providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
        elif "MIGraphXExecutionProvider" in available_providers:
            self._fallback_providers = ["ROCMExecutionProvider", "CPUExecutionProvider"]
        else:
            self._fallback_providers = ["CPUExecutionProvider"]

        # validate providers and provider_options before other initialization
        providers, provider_options = check_and_normalize_provider_args(
            providers, provider_options, available_providers
        )
        if not providers and len(available_providers) > 1:
            self.disable_fallback()
            raise ValueError(
                f"This ORT build has {available_providers} enabled. "
                "Since ORT 1.9, you are required to explicitly set "
                "the providers parameter when instantiating InferenceSession. For example, "
                f"onnxruntime.InferenceSession(..., providers={available_providers}, ...)"
            )

        session_options = self._sess_options if self._sess_options else C.get_default_session_options()
        if self._model_path:
            sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
        else:
>           sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
E           onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : custom_ops.cc:583 IsCompatible custom op schemas mismatch, expecting 1st input to keep same homogeneity

/nix/store/dgb45dn2i14434l1pl3pk0r4r0g0r9j3-python3.10-onnxruntime-1.15.1/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:426: Fail

```

### CODE REVIEW

**Comment by adityagoel4512** [comment]
I find it surprising it cannot cope with generic input types.

**Comment by adityagoel4512** [comment]
The right way to go about solving the original problem is probably to return a enum then.

**Comment by cbourjau** [comment]
> The right way to go about solving the original problem is probably to implement an enum then.

This will not solve the problem for the custom label encoder. That operator is only useful if it is implemented for several input and output types. This is orthogonal to "the enum" solution (i.e. if `get_attribute_tensor` should return an enum with one variant per element type rather than a concrete array).

**Comment by adityagoel4512** [comment]
https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#one-op-varied-types

Seems like the C++ api at least will support this in ORT 1.16

**Comment by cbourjau** [comment]
> https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#one-op-varied-types
> 
> Seems like the C++ api at least will support this in ORT 1.16

Nice! This PR introduced the necessary fix: https://github.com/microsoft/onnxruntime/pull/15184 . There was no change in the C-API so I expect this to Just Work™ With the upcoming release 🤞

**Comment by cbourjau** [comment]
> https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#one-op-varied-types
> 
> Seems like the C++ api at least will support this in ORT 1.16

Indeed! Things appear to be working as expected with ORT 1.16! 🎊

**Review by adityagoel4512 — APPROVED** [review]

**Pull request merged**
